export interface PostReddit {
  data: {
    approved_at_utc?: Date;
    subreddit: string;
    selftext: string;
    author_fullname: string;
    saved: boolean;
    mod_reason_title?: string;
    gilded: number;
    clicked: boolean;
    title: string;
    link_flair_richtext: Array<{
      e: string;
      t: string;
    }>;
    subreddit_name_prefixed: string;
    hidden: boolean;
    pwls: number;
    link_flair_css_class: string;
    downs: number;
    thumbnail_height?: number;
    top_awarded_type?: string;
    hide_score: boolean;
    name: string;
    quarantine: boolean;
    link_flair_text_color: string;
    upvote_ratio: number;
    author_flair_background_color?: string;
    subreddit_type: string;
    ups: number;
    total_awards_received: number;
    media_embed: {};
    thumbnail_width?: number;
    author_flair_template_id?: string;
    is_original_content: boolean;
    user_reports: never[];
    secure_media?: never;
    is_reddit_media_domain: boolean;
    is_meta: boolean;
    category?: string;
    secure_media_embed: {};
    link_flair_text: string;
    can_mod_post: boolean;
    score: number;
    approved_by?: string | null;
    is_created_from_ads_ui: boolean;
    author_premium: boolean;
    thumbnail: string;
    edited: number;
    author_flair_css_class?: string;
    author_flair_richtext: never[];
    gildings: {};
    content_categories?: never[];
    is_self: boolean;
    mod_note?: string | null;
    created: number;
    link_flair_type: string;
    wls: number;
    removed_by_category?: string | null;
    banned_by?: string | null;
    author_flair_type: string;
    domain: string;
    allow_live_comments: boolean;
    selftext_html: string;
    likes?: never;
    suggested_sort: string;
    banned_at_utc?: Date;
    view_count?: number;
    archived: boolean;
    no_follow: boolean;
    is_crosspostable: boolean;
    pinned: boolean;
    over_18: boolean;
    all_awardings: never[];
    awarders: never[];
    media_only: boolean;
    link_flair_template_id: string;
    can_gild: boolean;
    spoiler: boolean;
    locked: boolean;
    author_flair_text?: string;
    treatment_tags: never[];
    visited: boolean;
    removed_by?: string | null;
    num_reports?: number;
    distinguished?: string | null;
    subreddit_id: string;
    author_is_blocked: boolean;
    mod_reason_by?: string | null;
    removal_reason?: string | null;
    link_flair_background_color: string;
    id: string;
    is_robot_indexable: boolean;
    report_reasons?: never[];
    author: string;
    discussion_type?: string | null;
    num_comments: number;
    send_replies: boolean;
    contest_mode: boolean;
    mod_reports: never[];
    author_patreon_flair: boolean;
    author_flair_text_color?: string | null;
    permalink: string;
    stickied: boolean;
    url: string;
    subreddit_subscribers: number;
    created_utc: number;
    num_crossposts: number;
    media?: never;
    is_video: boolean;
  };
}

export interface PostsReddit {
  kind: string;
  data: {
    modhash: string;
    dist: number;
    children: Array<PostReddit>;
    after: string;
    before: string;
  };
}

export interface PostMongo {
  id: string;
  title: string;
  author: string;
  created_utc: string;
  ups: number;
  num_comments: number;
}
